# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# https://github.com/nodejs/release#release-schedule

name: ci
on:
  push:
    # branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]  # [macos-latest, ubuntu-latest, windows-latest]
        node-version: [10.x, 12.x, 14.x, 16.x, 18.x, 19.x]
        python-version: ['2.7']  # ['2.7', '3.11']  # NOTE: legacy Python!!
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-python@v4
        with:
          node-version: ${{ matrix.python-version }}
      - run: npm install --build-from-source
      - run: npm run lint
      - run: run test-cov
      - run: node custom-prebuild-ci
      - run: npm run coveralls
